// Theme colours
export const THEME = {
    NAVIGATION_BACKGROUND: "#f9faf9",
    ICON_COLOR: "#000000",
    MAIN_CONTENT_COLOR: "#ffffff",
    PROFILE_IMAGE_GRADIENT_START: "#f78531",
    PROFILE_IMAGE_GRADIENT_END: "#bd1480",
    ACTIVE_BACKGROUND: "#3897f0",
    SEPARATOR_COLOR: "#ebeceb",
    HASHTAG_COLOR: "#003569",
    INACTIVE_COLOR: "#b3b3b3",
    DOT_BACKGROUND: "#efefef",
    DIMMING_BACKGROUND: "rgba(0, 0, 0, .5)",
};
